FROM nginx:1.23.3-alpine

# remove the html folder from the nginx image
RUN rm -rf /usr/share/nginx/html/*

# remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Copy the nginx config file
COPY default.dev.conf /etc/nginx/conf.d/default.conf

# command to run on container start
CMD ["nginx", "-g", "daemon off;"]
