FROM php:8-fpm-alpine

LABEL maintainer="Omar IZEM <contact@izem.dev>"

# build args
ARG UID=1000
ARG GID=1000

# set user env vars
ENV UID=${UID} GID=${GID}

# workdir
WORKDIR /var/www/html

# install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# add user and group
RUN addgroup -g ${GID} --system yc-coding-challeng
RUN adduser -G yc-coding-challeng --system -D -s /bin/sh -u ${UID} yc-coding-challeng

# modify the php user to yc-coding-challeng ( to avoid permission issues )
RUN sed -i "s/user = www-data/user = yc-coding-challeng/g" /usr/local/etc/php-fpm.d/www.conf
RUN sed -i "s/group = www-data/group = yc-coding-challeng/g" /usr/local/etc/php-fpm.d/www.conf
RUN echo "php_admin_flag[display_errors] = on" >> /usr/local/etc/php-fpm.d/www.conf

# install phpredis
RUN apk add --no-cache --update --virtual .build-deps $PHPIZE_DEPS \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && apk del .build-deps

# install php extensions
RUN docker-php-ext-install pdo pdo_mysql

# install sqlite
RUN apk add --no-cache sqlite-dev \
    && docker-php-ext-install pdo_sqlite

# install GD extension
RUN apk add --no-cache libpng-dev libjpeg-turbo-dev libwebp-dev zlib-dev libxpm-dev \
    && docker-php-ext-configure gd --with-jpeg --with-webp --with-xpm \
    && docker-php-ext-install gd

# set user
USER yc-coding-challeng

# run php-fpm
CMD ["php-fpm", "-y", "/usr/local/etc/php-fpm.conf", "-R"]